dist: xenial
sudo: required
language: bash
services: 
  - docker
addons:
  apt:
    packages:
    - jq

jobs:
  include:
    - stage: test
      script:
        - git ls-files --exclude='*Dockerfile' --ignored | xargs --max-lines=1 -I{} sh -c 'docker run --rm -i -v ${PWD}/.hadolint.yaml:/.hadolint.yaml hadolint/hadolint < "$1"' -- {}
        - bash -c 'shopt -s globstar; shellcheck **/*.sh'
    - &build
      stage: build
      # set EXTRA_TAG to latest,stable when no more experimental versions for 0.17 come out
      env: VERSION_SHORT=0.17 EXTRA_TAG=latest
      script:
        - ./build.sh $VERSION_SHORT
    - <<: *build
      env: VERSION_SHORT=0.16
    - <<: *build
      env: VERSION_SHORT=0.15
    - <<: *build
      env: VERSION_SHORT=0.14
